# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

org: techtransformations
app: tooltime-backend
service: tooltime-backend
custom:
  secrets: ${file(secrets.${self:custom.stage}.json)}
  stage: 'local'
  amplify:
    - filename: ../tooltime-warehouse/src/aws-exports.js
      type: javascript
      appClient: CognitoUserPoolClient

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '1'

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-east-1
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DB_NAME: ${self:custom.secrets.DB_NAME}
    DB_USER: ${self:custom.secrets.DB_USER}
    DB_PASSWORD: ${self:custom.secrets.DB_PASSWORD}
    DB_HOST: ${self:custom.secrets.DB_HOST}
    DB_PORT: ${self:custom.secrets.DB_PORT}
  vpc:
    securityGroupIds:
      - ${self:custom.secrets.SECURITY_GROUP_ID}
    subnetIds:
      - ${self:custom.secrets.SUBNET1_ID}
      - ${self:custom.secrets.SUBNET2_ID}
      - ${self:custom.secrets.SUBNET3_ID}
      - ${self:custom.secrets.SUBNET4_ID}
      - ${self:custom.secrets.SUBNET5_ID}
      - ${self:custom.secrets.SUBNET6_ID}
  httpApi:
    cors: true

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - node_modules/**

functions:
  tooltime-backend:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
plugins: 
 - serverless-offline
 - aws-amplify-serverless-plugin

resources:
  - ${file(aws_resources/cognito-user-pool.yml)}
  - ${file(aws_resources/cognito-identity-pool.yml)}
#  - ${file(aws_resources/api-gateway-errors.yml)}
  - Resources:
      AWSLambdaVPCAccessExecutionRole:
        Type: AWS::IAM::ManagedPolicy
        Properties:
          Description: Creating policy for vpc connetion.
          Roles:
            - {"Ref" : "IamRoleLambdaExecution"}
          PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                Resource: "*"
